<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>marshall.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="marshall.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="MarshallWake.Service\**\*.cs" />
    <Compile Remove="MarshallWake.Service.Tests\**\*.cs" />
    <Content Remove="MarshallWake.Service\**\*" />
    <Content Remove="MarshallWake.Service.Tests\**\*" />
    <EmbeddedResource Remove="MarshallWake.Service\**\*" />
    <EmbeddedResource Remove="MarshallWake.Service.Tests\**\*" />
    <None Remove="MarshallWake.Service\**\*" />
    <None Remove="MarshallWake.Service.Tests\**\*" />
  </ItemGroup>

</Project>
